<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,1,0,'0MLOxdbQ0MQ=');
$cfg_Cs[3]=array(0,1,0,'u+HUsbWlzrs=');
$cfg_Cs[4]=array(0,1,0,'ucXV8rei1bk=');
$cfg_Cs[5]=array(0,1,0,'uavKvrmruOY=');
$cfg_Cs[6]=array(0,1,0,'ucXV8s7Eu68=');
$cfg_Cs[7]=array(0,1,0,'ucXV8s3GueM=');
$cfg_Cs[8]=array(0,1,0,'ucXV8srTxrU=');
$cfg_Cs[9]=array(0,1,0,'yMvO77fDzLg=');
$cfg_Cs[10]=array(0,1,0,'yr63trWlzrs=');
$cfg_Cs[11]=array(0,1,0,'16i80s3FttM=');
$cfg_Cs[12]=array(0,1,0,'u/q5ubzyvek=');
$cfg_Cs[13]=array(0,1,0,'ucXV8sLbzLM=');
$cfg_Cs[14]=array(0,1,1,'uaTX97avzKw=');
$cfg_Cs[15]=array(0,1,0,'1f6y37eoueY=');
?>