<?php
$z[0]=Array("myad","",24,54);
$z[0][4]['name']="top-banner";
$z[1]=Array("myad","",88,119);
$z[1][4]['name']="top-banner2";
$z[2]=Array("global","",198,226);
$z[2][4]['name']="cfg_memberurl";
$z[3]=Array("global","",907,932);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1110,1138);
$z[4][4]['name']="cfg_memberurl";
$z[5]=Array("global","",1265,1293);
$z[5][4]['name']="cfg_memberurl";
$z[6]=Array("channel","\r\n		<li><a href='[field:typeurl/]' [field:rel/] target='_blank'>[field:typename/]</a></li>\r\n	",1761,1903);
$z[6][4]['type']="top";
$z[6][4]['row']="14";

?>