<?php
$z[0]=Array("arclist","\r\n  			linkarr[[field:global.autoindex/]] = \"[field:arcurl/]\";\r\n  			picarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\n  			textarr[[field:global.autoindex/]] = \"[field:title function='html2text(@me)'/]\";\r\n  			",421,715);
$z[0][4]['typeid']="8";
$z[0][4]['type']="image";
$z[0][4]['row']="6";
$z[0][4]['titlelen']="100";
$z[1]=Array("arclist","\r\n          <li>\r\n            <span>[field:pubdate function=\"GetDateMK(@me)\"/]</span>\r\n            <a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a>\r\n          </li>\r\n        ",2087,2338);
$z[1][4]['typeid']="8";
$z[1][4]['row']="16";
$z[1][4]['titlelen']="100";
$z[2]=Array("myad","",2400,2429);
$z[2][4]['name']="index-ad1";
$z[3]=Array("myad","",2463,2492);
$z[3][4]['name']="index-ad2";

?>