<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",347,377);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",414,441);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1004,1042);
$z[4][4]['filename']="_header.htm";
$z[5]=Array("include","",1046,1084);
$z[5][4]['filename']="_block1.htm";
$z[6]=Array("include","",1088,1126);
$z[6][4]['filename']="_footer.htm";

?>